@extends('adminlte::page')
@section('title', 'Indicadores de Afluencia')
@section('content_header')
<div class="d-flex justify-content-between align-items-center flex-wrap" style="gap:10px;"><div><h1 class="mb-1">Indicadores de Afluencia</h1>@if($eleccionOperativa)<div class="text-muted">Elección operativa: <strong>{{ $eleccionOperativa->nombre }}</strong></div>@endif</div><div class="d-flex" style="gap:8px;"><a href="{{ route('admin.mesa_reportes.dashboard', ['eleccion_id' => $eleccionId]) }}" class="btn btn-outline-primary btn-sm">Dashboard</a><a href="{{ route('admin.mesa_reportes.afluencia', ['eleccion_id' => $eleccionId]) }}" class="btn btn-outline-primary btn-sm">Afluencia</a><a href="{{ route('admin.mesa_reportes.e14', ['eleccion_id' => $eleccionId]) }}" class="btn btn-outline-primary btn-sm">E14</a></div></div>
@stop
@section('content')
@include('admin.mesa_reportes.partials.filters')
@include('admin.mesa_reportes.partials.kpis')
<div class="row mb-3"><div class="col-md-3"><div class="info-box"><span class="info-box-icon bg-success"><i class="fas fa-clock"></i></span><div class="info-box-content"><span class="info-box-text">Corte 9:00</span><span class="info-box-number">{{ $kpis['mesas_afluencia_9'] }}</span></div></div></div><div class="col-md-3"><div class="info-box"><span class="info-box-icon bg-info"><i class="fas fa-clock"></i></span><div class="info-box-content"><span class="info-box-text">Corte 11:00</span><span class="info-box-number">{{ $kpis['mesas_afluencia_11'] }}</span></div></div></div><div class="col-md-3"><div class="info-box"><span class="info-box-icon bg-primary"><i class="fas fa-clock"></i></span><div class="info-box-content"><span class="info-box-text">Corte 2:00</span><span class="info-box-number">{{ $kpis['mesas_afluencia_14'] }}</span></div></div></div><div class="col-md-3"><div class="info-box"><span class="info-box-icon bg-warning"><i class="fas fa-check-double"></i></span><div class="info-box-content"><span class="info-box-text">3 cortes completos</span><span class="info-box-number">{{ $kpis['mesas_afluencia_completa'] }}</span></div></div></div></div>
<div class="card"><div class="card-header"><h3 class="card-title">Detalle por puesto</h3></div><div class="card-body table-responsive"><table class="table table-bordered table-sm"><thead><tr><th>Municipio</th><th>Puesto</th><th>Mesas</th><th>Afluencia</th><th>E14</th><th>Cierre</th></tr></thead><tbody>@foreach($resumenPuesto as $row)<tr><td>{{ $row['municipio'] }}</td><td>{{ $row['puesto'] }}</td><td>{{ $row['mesas_total'] }}</td><td>{{ $row['afluencia'] }}</td><td>{{ $row['e14'] }}</td><td>{{ $row['control'] }}</td></tr>@endforeach</tbody></table></div></div>
@stop
