@extends('adminlte::page')
@section('title', 'Dashboard Operativo')
@section('content_header')
<div class="d-flex justify-content-between align-items-center flex-wrap" style="gap:10px;"><div><h1 class="mb-1">Dashboard Operativo E14 + Afluencia</h1>@if($eleccionOperativa)<div class="text-muted">Elección operativa: <strong>{{ $eleccionOperativa->nombre }}</strong></div>@endif</div><div class="d-flex" style="gap:8px;"><a href="{{ route('admin.mesa_reportes.dashboard', ['eleccion_id' => $eleccionId]) }}" class="btn btn-outline-primary btn-sm">Dashboard</a><a href="{{ route('admin.mesa_reportes.afluencia', ['eleccion_id' => $eleccionId]) }}" class="btn btn-outline-primary btn-sm">Afluencia</a><a href="{{ route('admin.mesa_reportes.e14', ['eleccion_id' => $eleccionId]) }}" class="btn btn-outline-primary btn-sm">E14</a></div></div>
@stop
@section('content')
@include('admin.mesa_reportes.partials.filters')
@include('admin.mesa_reportes.partials.kpis')
<div class="row"><div class="col-md-3 mb-3"><div class="info-box"><span class="info-box-icon bg-gradient-info"><i class="fas fa-school"></i></span><div class="info-box-content"><span class="info-box-text">Puestos con coordinador</span><span class="info-box-number">{{ $kpis['puestos_con_coordinador'] }}</span></div></div></div><div class="col-md-3 mb-3"><div class="info-box"><span class="info-box-icon bg-gradient-danger"><i class="fas fa-exclamation-triangle"></i></span><div class="info-box-content"><span class="info-box-text">Reclamaciones</span><span class="info-box-number">{{ $kpis['mesas_reclamacion'] }}</span><small>Nuestras: {{ $kpis['reclamaciones_nuestras'] }} | Otros: {{ $kpis['reclamaciones_otros'] }}</small></div></div></div><div class="col-md-3 mb-3"><div class="info-box"><span class="info-box-icon bg-gradient-warning"><i class="fas fa-retweet"></i></span><div class="info-box-content"><span class="info-box-text">Mesas con reconteo</span><span class="info-box-number">{{ $kpis['mesas_reconteo'] }}</span></div></div></div><div class="col-md-3 mb-3"><div class="info-box"><span class="info-box-icon bg-gradient-secondary"><i class="fas fa-user-slash"></i></span><div class="info-box-content"><span class="info-box-text">Coordinadores sin actividad</span><span class="info-box-number">{{ $rezagos['coordinadores_sin_actividad']->count() }}</span></div></div></div></div>
<div class="row"><div class="col-lg-6"><div class="card"><div class="card-header"><h3 class="card-title">Avance por municipio</h3></div><div class="card-body table-responsive"><table class="table table-sm table-bordered"><thead><tr><th>Municipio</th><th>Mesas</th><th>Afluencia</th><th>E14</th><th>Cierre</th><th>Reclamaciones</th></tr></thead><tbody>@foreach($resumenMunicipio as $row)<tr><td>{{ $row['municipio'] }}</td><td>{{ $row['mesas_total'] }}</td><td>{{ $row['afluencia'] }}</td><td>{{ $row['e14'] }}</td><td>{{ $row['control'] }}</td><td>{{ $row['reclamaciones'] }}</td></tr>@endforeach</tbody></table></div></div></div><div class="col-lg-6"><div class="card"><div class="card-header"><h3 class="card-title">Avance por coordinador</h3></div><div class="card-body table-responsive"><table class="table table-sm table-bordered"><thead><tr><th>Coordinador</th><th>Mesas reportadas</th><th>E14</th><th>Cierre</th><th>Reclamaciones</th></tr></thead><tbody>@foreach($resumenCoordinador as $row)<tr><td>{{ $row['coordinador'] }}</td><td>{{ $row['mesas_reportadas'] }}</td><td>{{ $row['e14'] }}</td><td>{{ $row['control'] }}</td><td>{{ $row['reclamaciones'] }}</td></tr>@endforeach</tbody></table></div></div></div></div>
<div class="row"><div class="col-lg-4"><div class="card"><div class="card-header"><h3 class="card-title">Mesas sin afluencia</h3></div><div class="card-body table-responsive"><table class="table table-sm table-bordered"><thead><tr><th>Municipio</th><th>Puesto</th><th>Mesa</th></tr></thead><tbody>@foreach($rezagos['sin_afluencia']->take(80) as $row)<tr><td>{{ $row->municipio }}</td><td>{{ $row->puesto }}</td><td>{{ $row->mesa_num }}</td></tr>@endforeach</tbody></table></div></div></div><div class="col-lg-4"><div class="card"><div class="card-header"><h3 class="card-title">Afluencia sin E14</h3></div><div class="card-body table-responsive"><table class="table table-sm table-bordered"><thead><tr><th>Municipio</th><th>Puesto</th><th>Mesa</th></tr></thead><tbody>@foreach($rezagos['afluencia_sin_e14']->take(80) as $row)<tr><td>{{ $row->municipio }}</td><td>{{ $row->puesto }}</td><td>{{ $row->mesa_num }}</td></tr>@endforeach</tbody></table></div></div></div><div class="col-lg-4"><div class="card"><div class="card-header"><h3 class="card-title">E14 sin control final</h3></div><div class="card-body table-responsive"><table class="table table-sm table-bordered"><thead><tr><th>Municipio</th><th>Puesto</th><th>Mesa</th></tr></thead><tbody>@foreach($rezagos['e14_sin_control']->take(80) as $row)<tr><td>{{ $row->municipio }}</td><td>{{ $row->puesto }}</td><td>{{ $row->mesa_num }}</td></tr>@endforeach</tbody></table></div></div></div></div>
@stop
