@extends('adminlte::page')
@section('title', 'Indicadores E14')
@section('content_header')
<div class="d-flex justify-content-between align-items-center flex-wrap" style="gap:10px;"><div><h1 class="mb-1">Indicadores E14 y Reclamaciones</h1>@if($eleccionOperativa)<div class="text-muted">Elección operativa: <strong>{{ $eleccionOperativa->nombre }}</strong></div>@endif</div><div class="d-flex" style="gap:8px;"><a href="{{ route('admin.mesa_reportes.dashboard', ['eleccion_id' => $eleccionId]) }}" class="btn btn-outline-primary btn-sm">Dashboard</a><a href="{{ route('admin.mesa_reportes.afluencia', ['eleccion_id' => $eleccionId]) }}" class="btn btn-outline-primary btn-sm">Afluencia</a><a href="{{ route('admin.mesa_reportes.e14', ['eleccion_id' => $eleccionId]) }}" class="btn btn-outline-primary btn-sm">E14</a></div></div>
@stop
@section('content')
@include('admin.mesa_reportes.partials.filters')
@include('admin.mesa_reportes.partials.step_toggles')
@include('admin.mesa_reportes.partials.kpis')
<div class="row mb-3"><div class="col-md-3"><div class="info-box"><span class="info-box-icon bg-primary"><i class="fas fa-file-signature"></i></span><div class="info-box-content"><span class="info-box-text">E14 guardados</span><span class="info-box-number">{{ $kpis['mesas_e14'] }}</span></div></div></div><div class="col-md-3"><div class="info-box"><span class="info-box-icon bg-warning"><i class="fas fa-retweet"></i></span><div class="info-box-content"><span class="info-box-text">Con reconteo</span><span class="info-box-number">{{ $kpis['mesas_reconteo'] }}</span></div></div></div><div class="col-md-3"><div class="info-box"><span class="info-box-icon bg-danger"><i class="fas fa-exclamation-circle"></i></span><div class="info-box-content"><span class="info-box-text">Con reclamación</span><span class="info-box-number">{{ $kpis['mesas_reclamacion'] }}</span></div></div></div><div class="col-md-3"><div class="info-box"><span class="info-box-icon bg-success"><i class="fas fa-camera"></i></span><div class="info-box-content"><span class="info-box-text">Fotos cargadas</span><span class="info-box-number">{{ $rows->whereNotNull('reclamacion_foto_path')->count() }}</span></div></div></div></div>
<div class="card"><div class="card-header"><h3 class="card-title">Detalle E14 por mesa</h3></div><div class="card-body table-responsive"><table class="table table-bordered table-sm"><thead><tr><th>Municipio</th><th>Puesto</th><th>Mesa</th><th>Coordinador</th><th>E14</th><th>Reconteo</th><th>Reclamación</th><th>Jurados firmaron</th><th>Control</th></tr></thead><tbody>@foreach($rows as $row)<tr><td>{{ $row->municipio }}</td><td>{{ $row->puesto }}</td><td>{{ $row->mesa_num }}</td><td>{{ $row->coordinador_nombre ?: 'N/D' }}</td><td>{{ $row->e14_reportado_at ? 'Sí' : 'No' }}</td><td>{{ (int) $row->reconteo === 1 ? 'Sí' : 'No' }}</td><td>@if((int) $row->reclamacion === 1) {{ $row->reclamacion_origen === 'nuestra' ? 'Nuestra' : 'Otro candidato' }} @else No @endif</td><td>{{ $row->jurados_firmaron ?? '-' }}</td><td>{{ $row->control_final_at ? 'Completo' : 'Pendiente' }}</td></tr>@endforeach</tbody></table></div></div>
@stop
